version: '3.7'

networks:
  buffered-file-reader-network:
    name: buffered-file-reader-network
    driver: bridge

services:
  application:
    container_name: buffered-file-reader
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - buffered-file-reader-network
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: node
    env_file:
      - ./workspace.env
